//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsIndiaTVEntities : DbContext
    {
        public NewsIndiaTVEntities()
            : base("name=NewsIndiaTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attachment> Attachments { get; set; }
        public DbSet<AuthenticationLink> AuthenticationLinks { get; set; }
        public DbSet<CategoryMaster> CategoryMasters { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<SideBannerMaster> SideBannerMasters { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<SubCategoryDataAttachment> SubCategoryDataAttachments { get; set; }
        public DbSet<SubCategoryDataMaster> SubCategoryDataMasters { get; set; }
        public DbSet<SubCategoryMaster> SubCategoryMasters { get; set; }
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<Verification> Verifications { get; set; }
    }
}
