//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryDataAttachment
    {
        public int ID { get; set; }
        public int SubCategoryDataID { get; set; }
        public string FileName { get; set; }
        public int AttachmentID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual SubCategoryDataMaster SubCategoryDataMaster { get; set; }
    }
}
