//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthenticationLink
    {
        public int Id { get; set; }
        public int VerificationTypeId { get; set; }
        public int UserId { get; set; }
        public string UnqiueLink { get; set; }
        public bool IsUsed { get; set; }
    
        public virtual Verification Verification { get; set; }
    }
}
