//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryMaster
    {
        public SubCategoryMaster()
        {
            this.SubCategoryDataMasters = new HashSet<SubCategoryDataMaster>();
        }
    
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string SubCategoryName { get; set; }
        public bool IsVisible { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual ICollection<SubCategoryDataMaster> SubCategoryDataMasters { get; set; }
    }
}
