//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryDataMaster
    {
        public SubCategoryDataMaster()
        {
            this.SubCategoryDataAttachments = new HashSet<SubCategoryDataAttachment>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SavedTimeStamp { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public int SubCategoryId { get; set; }
        public Nullable<bool> IsSuperAdminApproved { get; set; }
        public bool IsVisible { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SubCategoryDataAttachment> SubCategoryDataAttachments { get; set; }
        public virtual SubCategoryMaster SubCategoryMaster { get; set; }
    }
}
