//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.States = new HashSet<State>();
            this.States1 = new HashSet<State>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string City { get; set; }
        public int CountryID { get; set; }
        public int StateID { get; set; }
        public string Address { get; set; }
        public int RoleId { get; set; }
        public Nullable<bool> HasUserAccess { get; set; }
        public Nullable<bool> HasMenuAccess { get; set; }
        public Nullable<bool> HasNewsAccess { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<State> States { get; set; }
        public virtual ICollection<State> States1 { get; set; }
        public virtual State State { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
